---
# tasks file for director-temp
- name: Set hosts file
  shell: echo "$( ifconfig ens3 | grep 'inet ' | awk '{ print $2 }') $(hostname -s )" > /etc/hosts  

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent

# enable routing
- name: Download repository file
  get_url:
    url: http://{{ apt_repo_ip }}/sources.list.debian
    dest: /etc/apt/sources.list

- name: Download Docker GPG fike
  get_url:
    url: http://{{ apt_repo_ip }}/docker.gpg
    #dest: /etc/apt/keyrings/docker.gpg
    dest: /etc/apt/trusted.gpg.d/docker.gpg

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true



#udo iptables -t nat -A PREROUTING 
#-i eth0 -p tcp --dport 80 -j DNAT --to-destination 10.0.0.1
##sudo iptables -t nat -A POSTROUTING #
#-o eth1 -p tcp --dport 80 -d 10.0.0.1 -j SNAT --to-source 10.0.0.2