---
# tasks file for deployment
- name: certificates
  ansible.builtin.command: 
    cmd: kolla-ansible certificates -i inventory 
    chdir: /etc/kolla
  when: kolla_ssl is defined and kolla_ssl == "yes"

- name: pre-checs
  ansible.builtin.command: 
    cmd: kolla-ansible prechecks -i inventory 
    chdir: /etc/kolla

- name: deploy
  ansible.builtin.command: 
    cmd: kolla-ansible deploy -i inventory 
    chdir: /etc/kolla

- name: post-deploy
  ansible.builtin.command: 
    cmd: kolla-ansible post-deploy -i inventory 
    chdir: /etc/kolla

- name: Set SSL CA adminrc
  ansible.builtin.lineinfile:
    line: "export OS_CACERT=/etc/kolla/certificates/ca/root.crt"
    path: "/etc/kolla/admin-openrc.sh"
  when: kolla_ssl is defined and kolla_ssl == "yes"

- name: Show admin password
  ansible.builtin.shell:
    cmd: "cat /etc/kolla/admin-openrc.sh  | grep PASS | cut -d = -f 2"
    executable: /bin/bash
  register: AdminPass

- debug: msg="Admin password {{ AdminPass.stdout }}"

- debug: msg="Login url https://{{ kolla_internal_address }}"
  when: kolla_ssl is defined and kolla_ssl == 'yes'

- debug: msg="Login url http://{{ kolla_internal_address }}"
  when: kolla_ssl is not defined or kolla_ssl == 'no'