# Address to access openstack
kolla_internal_address: 10.17.4.60

# My registry, if dont have anymore the 2024 imagens on oficial repos
# if want to use oficial repo, simply comment that line
docker_local_repo: registry.bluetechlabs.com.br

#docker_local_repo: 10.17.4.1:5000 #to use a full local
#dockar_local_repo_insecure: yes # if dont have https on local

# I have a copy of old versions too
repo: https://github.com/marcusgrenfell/kolla-ansible
version: stable/2024.2

# If you is using a loca repo, this save you to have also docker repo
kolla_container_engine: podman
#apt_repos:
#  - 'deb http://192.168.15.109/ubuntu/ jammy main universe'
#  - 'deb http://192.168.15.109/ubuntu/ jammy-updates main universe'

#some options
cirros_image: https://github.com/cirros-dev/cirros/releases/download/0.6.3/cirros-0.6.3-x86_64-disk.img
enable_grafana: no
enable_prometheus: no
enable_skyline: no
kolla_ssl: 'no'