---
# tasks file for director
- name: Create kolla folder
  ansible.builtin.file:
    state: directory
    path: /etc/kolla
    owner: root
    group: root
    mode: '0644'

- name: Copy openstack config files
  copy:
    src: files/globals.yml
    dest: "/etc/kolla"

- name: Copy inventory machines 
  copy:
    src: "{{ inventory_dir }}/inventory"
    dest: "/etc/kolla/inventory"

- name: Copy inventory template
  ansible.builtin.lineinfile:
    line: "{{ lookup('file', 'files/multinode') }}"
    path: "/etc/kolla/inventory"

- name: Install Base packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    allow_downgrade: yes
  with_items: 
    - git
    - python3-dev
    - libffi-dev
    - gcc
    - libssl-dev
    - python3-venv
    - python3-pip
    - htop
    - tmux
    - sshpass
    - net-tools
    - docker-ce

- name: Install ansible
  ansible.builtin.pip:
    name: 'ansible-core==2.15'

- name: Clone kolla-ansible
  ansible.builtin.git:
    repo: 'https://opendev.org/openstack/kolla-ansible'
    dest: /root/kolla-ansible
    #version: master
    version: stable/2023.2

- name: Install kolla-ansible
  ansible.builtin.pip:
    chdir: /root
    name: ./kolla-ansible
  
- name: Install kolla deps
  ansible.builtin.command: 
    cmd: kolla-ansible install-deps

- name: Install openstack client
  ansible.builtin.pip:
    name: 'python-openstackclient'

- name: Copy password template file
  copy:
    remote_src: true
    src: /root/kolla-ansible/etc/kolla/passwords.yml
    dest: /etc/kolla

- name: Generate new passwords
  ansible.builtin.command: 
    cmd: python3 ./generate_passwords.py
    chdir: /root/kolla-ansible/tools

- name: Set hosts file
  shell: echo "$( ifconfig ens3 | grep 'inet ' | awk '{ print $2 }') $(hostname -s )" > /etc/hosts  

#- meta: end_play

- name: Bootstrap
  ansible.builtin.command: 
    cmd: kolla-ansible -i inventory bootstrap-servers
    chdir: /etc/kolla

- name: pre-checs
  ansible.builtin.command: 
    cmd: kolla-ansible -i inventory prechecks
    chdir: /etc/kolla
  
- name: deploy
  ansible.builtin.command: 
    cmd: kolla-ansible -i inventory deploy
    chdir: /etc/kolla

- name: post-deploy
  ansible.builtin.command: 
    cmd: kolla-ansible -i inventory post-deploy
    chdir: /etc/kolla

- name: Download Cirros image
  get_url:
    url: http://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
    dest: /root