- name: Repository config
  hosts: compute,control,deployment
  roles:
    - repository-config
    - setswap

- name: Configure deployment
  hosts: deployment
  roles:
    - pre-deployment

- name: Configure Ceph
  hosts: ceph,deployment
  roles:
    - ceph

- name: Configure deployment
  hosts: deployment
  roles:
    - deployment
    - initial-openstack-config
    